### ISSUE TITLE
Application crash at Serialise_InitialState

### ISSUE THREAD

**Issue by szihs** [baldurk/renderdoc#1226]
Hello, 
Please check the issue when application running under renderdoc context

```
#2  0xb4323b82 in vkMapMemory () from /tmp/libmali.so
#3  0xb3cc50bc in WrappedVulkan::Serialise_InitialState<WriteSerialiser> (this=0x522110, ser=..., id=...) at /usr/src/debug/renderdoc-1.3/renderdoc/driver/vulkan/vk_initstate.cpp:1013
#4  0xb3c4b5ca in ResourceManager<VulkanResourceManagerConfiguration>::InsertInitialContentsChunks (this=0xc56c8, ser=...) at /usr/src/debug/renderdoc-1.3/renderdoc/core/resource_manager.h:998
#5  0xb3c37cd4 in WrappedVulkan::EndFrameCapture (this=0x522110, dev=<optimized out>, wnd=<optimized out>) at /usr/src/debug/renderdoc-1.3/renderdoc/driver/vulkan/vk_core.cpp:1650
#6  0xb3ee5208 in RenderDoc::EndFrameCapture (this=0xb42075c0 <RenderDoc::Inst()::realInst>, dev=dev@entry=0x684f0, wnd=wnd@entry=0x2cab0) at /usr/src/debug/renderdoc-1.3/renderdoc/core/core.cpp:523
#7  0xb3c322ec in WrappedVulkan::Present (this=this@entry=0x522110, dev=0x684f0, wnd=0x2cab0) at /usr/src/debug/renderdoc-1.3/renderdoc/driver/vulkan/vk_core.cpp:1747
#8  0xb3deb7e6 in WrappedVulkan::vkQueuePresentKHR (this=0x522110, queue=0x322098, pPresentInfo=<optimized out>) at /usr/src/debug/renderdoc-1.3/renderdoc/driver/vulkan/wrappers/vk_wsi_funcs.cpp:783
```
Inspecting frame 3 with gdb
```
(gdb) f 3
#3  0xb3cc50bc in WrappedVulkan::Serialise_InitialState<WriteSerialiser> (this=0x522110, ser=..., id=...) at /usr/src/debug/renderdoc-1.3/renderdoc/driver/vulkan/vk_initstate.cpp:1013
1013    in /usr/src/debug/renderdoc-1.3/renderdoc/driver/vulkan/vk_initstate.cpp
(gdb) p id
$8 = {id = 145}
(gdb) info locals
range = {sType = VK_STRUCTURE_TYPE_APPLICATION_INFO, pNext = 0x0, memory = {handle = 0}, offset = 17952, size = 81172133134106072}
IsSparse = false
mappedMem = {mem = {handle = 0}, offs = 0, size = 0, scope = <optimized out>, type = <optimized out>, memoryTypeIndex = <optimized out>, buffer = <optimized out>}
deserialise_1003 = {m_Ser = @0xbe7fecc0, m_El = @0xbe7fe8a8}
ContentsSize = 0
initContents = {descriptorSlots = 0x0, descriptorWrites = 0x0, descriptorInfo = 0x0, numDescriptors = 0, type = eResUnknown, buf = {handle = 0}, img = {handle = 0}, mem = {mem = {handle = 0}, offs = 0, size = 0, scope = MemoryScope::InitialContents, type = MemoryType::Upload, memoryTypeIndex = 0, buffer = false}, tag = VkInitialContents::BufferCopy, {sparseBuffer = {binds = 0x0, numBinds = 0, memDataOffs = 0x0, numUniqueMems = 0, totalSize = 0}, sparseImage = {opaque = 0x0, opaqueCount = 0, imgdim = {width = 0, height = 0, depth = 0}, pagedim = {width = 0, height = 0, depth = 0}, pages = {0x0, 0x0, 0x0, 0x0}, pageCount = {0, 0, 0, 0}, pageBinds = {0x0, 0x0, 0x0, 0x0}, memDataOffs = 0x0, numUniqueMems = 0, totalSize = 0}}}
vkr = VK_SUCCESS
uploadMemory = {mem = {handle = 0}, offs = 0, size = 0, scope = MemoryScope::InitialContents, type = MemoryType::GPULocal, memoryTypeIndex = 0, buffer = <optimized out>}
uploadBuf = {handle = 0}
deserialise_977 = {m_Ser = @0xbe7fecc0, m_El = @0xbe7fe897}
Contents = 0x0
__PRETTY_FUNCTION__ = "bool WrappedVulkan::Serialise_InitialState(SerialiserType&, ResourceId, WrappedVkRes*) [with SerialiserType = WriteSerialiser]"
type = eResImage
record = <optimized out>
ret = true
deserialise_730 = {m_Ser = @0xbe7fecc0, m_El = @0xbe7fe898}
deserialise_731 = {m_Ser = @0xbe7fecc0, m_El = @0xbe7fe888}
(gdb)p initContents
$9 = {descriptorSlots = 0x0, descriptorWrites = 0x0, descriptorInfo = 0x0, numDescriptors = 0, type = eResUnknown, buf = {handle = 0}, img = {handle = 0}, mem = {mem = {handle = 0}, offs = 0, size = 0, scope = MemoryScope::InitialContents, type = MemoryType::Upload, memoryTypeIndex = 0, buffer = false}, tag = VkInitialContents::BufferCopy, {sparseBuffer = {binds = 0x0, numBinds = 0, memDataOffs = 0x0, numUniqueMems = 0, totalSize = 0}, sparseImage = {opaque = 0x0, opaqueCount = 0, imgdim = {width = 0, height = 0, depth = 0}, pagedim = {width = 0, height = 0, depth = 0}, pages = {0x0, 0x0, 0x0, 0x0}, pageCount = {0, 0, 0, 0}, pageBinds = {0x0, 0x0, 0x0, 0x0}, memDataOffs = 0x0, numUniqueMems = 0, totalSize = 0}}}
(gdb) q
```

It looks the id = 145 was not mapped from the .log file and enteries are `0x0`
```

OC 010107: [05:48:57]             core.cpp( 312) - Log     - RenderDoc v1.3 32-bit Development (NO_GIT_COMMIT_HASH_DEFINED) capturing application
RDOC 010107: [05:48:57]   posix_libentry.cpp(  69) - Log     - Loading into /usr/bin/vkvr360
RDOC 010107: [05:48:57]         vk_layer.cpp(  53) - Log     - Registering Vulkan hooks
RDOC 010107: [05:48:57]  vk_device_funcs.cpp( 569) - Log     - Initialised capture layer in Vulkan instance.
RDOC 010107: [05:48:57]  vk_device_funcs.cpp( 944) - Log     - physical device 0: Mali-G51 (ver 879.688 patch 0xc3e) - 13b5:70901000
RDOC 010107: [05:48:57]          vk_core.cpp( 999) - Warning - Spec versions of VK_EXT_debug_marker are different between supported extension (4) and reported (3)!
RDOC 010107: [05:48:57]          vk_core.cpp( 999) - Warning - Spec versions of VK_KHR_maintenance1 are different between supported extension (2) and reported (1)!
RDOC 010107: [05:48:57]          vk_core.cpp( 999) - Warning - Spec versions of VK_KHR_swapchain are different between supported extension (70) and reported (68)!
RDOC 010107: [05:48:57]          vk_core.cpp( 999) - Warning - Spec versions of VK_EXT_debug_marker are different between supported extension (4) and reported (3)!
RDOC 010107: [05:48:57]          vk_core.cpp( 999) - Warning - Spec versions of VK_KHR_maintenance1 are different between supported extension (2) and reported (1)!
RDOC 010107: [05:48:57]          vk_core.cpp( 999) - Warning - Spec versions of VK_KHR_swapchain are different between supported extension (70) and reported (68)!
RDOC 010107: [05:48:57]          vk_core.cpp( 999) - Warning - Spec versions of VK_EXT_debug_marker are different between supported extension (4) and reported (3)!
RDOC 010107: [05:48:57]          vk_core.cpp( 999) - Warning - Spec versions of VK_KHR_maintenance1 are different between supported extension (2) and reported (1)!
RDOC 010107: [05:48:57]          vk_core.cpp( 999) - Warning - Spec versions of VK_KHR_swapchain are different between supported extension (70) and reported (68)!
RDOC 010107: [05:48:57]          vk_core.cpp( 999) - Warning - Spec versions of VK_EXT_debug_marker are different between supported extension (4) and reported (3)!
RDOC 010107: [05:48:57]          vk_core.cpp( 999) - Warning - Spec versions of VK_KHR_maintenance1 are different between supported extension (2) and reported (1)!
RDOC 010107: [05:48:57]          vk_core.cpp( 999) - Warning - Spec versions of VK_KHR_swapchain are different between supported extension (70) and reported (68)!
RDOC 010107: [05:48:57]  vk_device_funcs.cpp(2090) - Warning - shaderStorageImageMultisample = false, save/load from 2DMS textures will not be possible
RDOC 010107: [05:48:57]  vk_device_funcs.cpp(2107) - Warning - pipelineStatisticsQuery = false, pipeline counters will not work
RDOC 010107: [05:48:58]       shader_cache.h( 139) - Debug   - Successfully loaded 86 shaders from shader cache
RDOC 010107: [05:48:58]         vk_debug.cpp( 532) - Debug   - Depth copies Array -> MSAA not supported for sample count 2 on format VK_FORMAT_D16_UNORM
RDOC 010107: [05:48:58]         vk_debug.cpp( 532) - Debug   - Depth copies Array -> MSAA not supported for sample count 16 on format VK_FORMAT_D16_UNORM
RDOC 010107: [05:48:58]         vk_debug.cpp( 493) - Debug   - Depth copies MSAA -> Array not supported for format VK_FORMAT_D16_UNORM_S8_UINT
RDOC 010107: [05:48:58]         vk_debug.cpp( 532) - Debug   - Depth copies Array -> MSAA not supported for sample count 2 on format VK_FORMAT_X8_D24_UNORM_PACK32
RDOC 010107: [05:48:58]         vk_debug.cpp( 532) - Debug   - Depth copies Array -> MSAA not supported for sample count 16 on format VK_FORMAT_X8_D24_UNORM_PACK32
RDOC 010107: [05:48:58]         vk_debug.cpp( 532) - Debug   - Depth copies Array -> MSAA not supported for sample count 2 on format VK_FORMAT_D24_UNORM_S8_UINT
RDOC 010107: [05:48:58]         vk_debug.cpp( 532) - Debug   - Depth copies Array -> MSAA not supported for sample count 16 on format VK_FORMAT_D24_UNORM_S8_UINT
RDOC 010107: [05:48:58]         vk_debug.cpp( 532) - Debug   - Depth copies Array -> MSAA not supported for sample count 2 on format VK_FORMAT_D32_SFLOAT
RDOC 010107: [05:48:59]         vk_debug.cpp( 532) - Debug   - Depth copies Array -> MSAA not supported for sample count 16 on format VK_FORMAT_D32_SFLOAT
RDOC 010107: [05:48:59]         vk_debug.cpp( 493) - Debug   - Depth copies MSAA -> Array not supported for format VK_FORMAT_D32_SFLOAT_S8_UINT
RDOC 010107: [05:48:59] vk_resource_funcs.cpp(1581) - Debug   - External image requires 11059200 bytes at 16 alignment, in 3 memory types
RDOC 010107: [05:48:59] vk_resource_funcs.cpp(1584) - Debug   - Non-external version requires 11059200 bytes at 64 alignment, in 3 memory types
RDOC 010107: [05:48:59] vk_resource_funcs.cpp(1581) - Debug   - External image requires 11059200 bytes at 16 alignment, in 3 memory types
RDOC 010107: [05:48:59] vk_resource_funcs.cpp(1584) - Debug   - Non-external version requires 11059200 bytes at 64 alignment, in 3 memory types
RDOC 010107: [05:49:06]         streamio.cpp( 319) - Warning - Error reading from socket
RDOC 010107: [05:49:11]   resource_manager.h( 861) - Debug   - Preparing up to 18 potentially dirty resources
RDOC 010107: [05:49:11]        vk_memory.cpp( 189) - Debug   - Allocating 0x708000 with alignment 0x40 in 0x3 for a buffer (Readback in InitialContents)
RDOC 010107: [05:49:11]        vk_memory.cpp( 253) - Debug   - No available block found - allocating new block
RDOC 010107: [05:49:11]        vk_memory.cpp( 303) - Debug   - Creating new allocation of 0x2000000 bytes
RDOC 010107: [05:49:12]        vk_memory.cpp( 189) - Debug   - Allocating 0x5eec00 with alignment 0x40 in 0x3 for a buffer (Readback in InitialContents)
RDOC 010107: [05:49:12]        vk_memory.cpp( 201) - Debug   - Considering block 0: memory type 0 and type Readback. Total size 0x2000000, current offset 0x708000, last alloc was buffer
RDOC 010107: [05:49:12]        vk_memory.cpp( 231) - Debug   - At next offset 0x708000, there's 0x18f8000 bytes available for 0x5eec00 bytes requested
RDOC 010107: [05:49:12]        vk_memory.cpp( 244) - Debug   - Allocating using this block: 0x708000 -> 0xcf6c00
RDOC 010107: [05:49:12]     vk_initstate.cpp( 124) - Warning - Image ResourceId::140 in external/foreign queue family, initial contents impossible to fetch.
RDOC 010107: [05:49:12]     vk_initstate.cpp( 124) - Warning - Image ResourceId::145 in external/foreign queue family, initial contents impossible to fetch.
RDOC 010107: [05:49:12]   resource_manager.h( 892) - Debug   - Prepared 9 dirty resources
RDOC 010107: [05:49:12]   resource_manager.h( 908) - Debug   - Force-prepared 0 dirty resources
RDOC 010107: [05:49:12]          vk_core.cpp(1311) - Debug   - Attempting capture
RDOC 010107: [05:49:12]          vk_core.cpp(1329) - Log     - Starting capture, frame 17
RDOC 010107: [05:49:12]   vk_queue_funcs.cpp( 925) - Debug   - Map of memory 135 not referenced in this queue - not flushing
RDOC 010107: [05:49:12]   vk_queue_funcs.cpp( 925) - Debug   - Map of memory 137 not referenced in this queue - not flushing
RDOC 010107: [05:49:12]   vk_queue_funcs.cpp( 925) - Debug   - Map of memory 139 not referenced in this queue - not flushing
RDOC 010107: [05:49:12]   vk_queue_funcs.cpp( 925) - Debug   - Map of memory 128 not referenced in this queue - not flushing
RDOC 010107: [05:49:12]   vk_queue_funcs.cpp( 972) - Log     - Persistent map flush forced for 135 (0 -> 3010752)
RDOC 010107: [05:49:12]   vk_queue_funcs.cpp( 972) - Log     - Persistent map flush forced for 137 (0 -> 98304)
RDOC 010107: [05:49:12]   vk_queue_funcs.cpp( 925) - Debug   - Map of memory 139 not referenced in this queue - not flushing
RDOC 010107: [05:49:12]   vk_queue_funcs.cpp( 925) - Debug   - Map of memory 128 not referenced in this queue - not flushing
RDOC 010107: [05:49:12]          vk_core.cpp(1355) - Log     - Finished capture, Frame 18
RDOC 010107: [05:49:12]        vk_memory.cpp( 189) - Debug   - Allocating 0x7e9000 with alignment 0x40 in 0x3 for a buffer (Readback in InitialContents)
RDOC 010107: [05:49:12]        vk_memory.cpp( 201) - Debug   - Considering block 0: memory type 0 and type Readback. Total size 0x2000000, current offset 0xcf6c00, last alloc was buffer
RDOC 010107: [05:49:12]        vk_memory.cpp( 231) - Debug   - At next offset 0xcf6c00, there's 0x1309400 bytes available for 0x7e9000 bytes requested
RDOC 010107: [05:49:12]        vk_memory.cpp( 244) - Debug   - Allocating using this block: 0xcf6c00 -> 0x14dfc00
RDOC 010107: [05:49:13]          rdcfile.cpp( 660) - Debug   - creating RDC file.
RDOC 010107: [05:49:13]          rdcfile.cpp( 668) - Debug   - Opened capture file for write
RDOC 010107: [05:49:13]       serialiser.cpp( 393) - Debug   - Chunk estimated at 307 bytes, actual length 207. Added 100 bytes padding.
RDOC 010107: [05:49:13]          vk_core.cpp(1646) - Debug   - Inserting Resource Serialisers
RDOC 010107: [05:49:13]   resource_manager.h( 813) - Debug   - 36 frame resource records
RDOC 010107: [05:49:13]   resource_manager.h( 848) - Debug   - 52 frame resource chunks
RDOC 010107: [05:49:13]   resource_manager.h( 853) - Debug   - inserted to serialiser
RDOC 010107: [05:49:13]   resource_manager.h( 919) - Debug   - Checking 18 possibly dirty resources
RDOC 010107: [05:49:13]       serialiser.cpp( 393) - Debug   - Chunk estimated at 6220992 bytes, actual length 6220832. Added 160 bytes padding.
```

It looks like side affect of https://github.com/baldurk/renderdoc/commit/e3b50d2377888b052da341b7bfe97eb807ffb778

Please check.

**Comment by baldurk** [comment]
I believe that commit should fix the crash you were seeing, but I don't have a good repro for this case so please let me know if you still have issues.
