### ISSUE TITLE
vkGetInstanceProcAddr returns null for vkCmdDebugMarkerBeginEXT in 32 bit arch

### ISSUE THREAD

**Issue by SamVanheer** [baldurk/renderdoc#1419]
## Description

When using RenderDoc to debug a 32 bit application using Vulkan, the `vkCmdDebugMarkerBeginEXT` extension function fails to be loaded by `vkGetInstanceProcAddr`. Instead a null pointer is returned.

## Repro steps

This is easy to reproduce using Veldrid: https://github.com/mellinoe/veldrid

Veldrid comes with a sample application called NeoDemo. This has support for in-application debugging which is how i encountered this issue.

Compile NeoDemo, then go to the directory containing the dll. For me this is `veldrid\bin\Debug\NeoDemo\netcoreapp2.0`.

You'll need the Net Core SDK to compile this program. I have both the x64 and x86 SDKs installed but i think either one is sufficient to compile it: https://dotnet.microsoft.com/download/dotnet-core/2.2

In the `native\win-x86` directory you'll find the 32 bit version of SDL2 that you'll need to copy to the `netcoreapp2.0` directory to successfully load this dll.

Place the x86 `renderdoc.dll` in the same directory so it can be loaded, or install it so the automatic dll lookup can find it in the `Program Files (x86)\RenderDoc` installation directory.

Then launch NeoDemo in 32 bit mode. You'll need to have the Net Core x86 Runtime installed for this: https://dotnet.microsoft.com/download/dotnet-core/2.2

Then run it using this command line:
```
cd veldrid\bin\Debug\NeoDemo\netcoreapp2.0
"C:\Program Files (x86)\dotnet\dotnet.exe" NeoDemo.dll
```

Then go to `Settings->Graphics Backend` and choose `Vulkan`.

Then go to `RenderDoc` and choose `Load`. This will load the in-application RenderDoc instance, followed by recreating the window and graphics backend.

At this point the program will crash with this stack trace:
```
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDelegate](IntPtr ptr)
   at Veldrid.Vk.VkGraphicsDevice.CreateLogicalDevice(VkSurfaceKHR surface, Boolean preferStandardClipY, VulkanDeviceOptions options) in C:\Users\Sam\Documents\GitHub\veldrid\src\Veldrid\Vk\VkGraphicsDevice.cs:line 747
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc, VulkanDeviceOptions vkOptions) in C:\Users\Sam\Documents\GitHub\veldrid\src\Veldrid\Vk\VkGraphicsDevice.cs:line 119
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc) in C:\Users\Sam\Documents\GitHub\veldrid\src\Veldrid\Vk\VkGraphicsDevice.cs:line 106
   at Veldrid.GraphicsDevice.CreateVulkan(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription) in C:\Users\Sam\Documents\GitHub\veldrid\src\Veldrid\GraphicsDevice.cs:line 974
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, Boolean colorSrgb) in C:\Users\Sam\Documents\GitHub\veldrid\src\Veldrid.StartupUtilities\VeldridStartup.cs:line 222
   at Veldrid.StartupUtilities.VeldridStartup.CreateVulkanGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window) in C:\Users\Sam\Documents\GitHub\veldrid\src\Veldrid.StartupUtilities\VeldridStartup.cs:line 209
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend) in C:\Users\Sam\Documents\GitHub\veldrid\src\Veldrid.StartupUtilities\VeldridStartup.cs:line 112
   at Veldrid.NeoDemo.NeoDemo.ChangeBackend(GraphicsBackend backend) in C:\Users\Sam\Documents\GitHub\veldrid\src\NeoDemo\NeoDemo.cs:line 618
   at Veldrid.NeoDemo.NeoDemo.Update(Single deltaSeconds) in C:\Users\Sam\Documents\GitHub\veldrid\src\NeoDemo\NeoDemo.cs:line 397
   at Veldrid.NeoDemo.NeoDemo.Run() in C:\Users\Sam\Documents\GitHub\veldrid\src\NeoDemo\NeoDemo.cs:line 228
   at Veldrid.NeoDemo.Program.Main(String[] args) in C:\Users\Sam\Documents\GitHub\veldrid\src\NeoDemo\Program.cs:line 9
```

The code in question can be found here:
https://github.com/mellinoe/veldrid/blob/8a03f3a4a68277e9f3ce1b0762ddb4bf1cf3011a/src/Veldrid/Vk/VkGraphicsDevice.cs#L743-L753

The debug marker extension was reported as available, but a null pointer is returned.

## Environment

* RenderDoc build: v1.4
* Operating System: Windows 8.1
* API: Vulkan

As you can probably tell i encountered this issue in a C# program that is performing P/Invoke calls to native code. This code works perfectly in the x64 version, it returns the function pointer as expected.

**Comment by baldurk** [comment]
This appears to be an application bug. In your invoke code when encoding a UTF-8 string to pass to vkGetInstanceProcAddr you don't allocate any space for a NULL terminator so the name that gets through contains trailing garbage:

```csharp
        private IntPtr GetInstanceProcAddr(string name)
        {
            int byteCount = Encoding.UTF8.GetByteCount(name);
            byte* utf8Ptr = stackalloc byte[byteCount];

            fixed (char* namePtr = name)
            {
                Encoding.UTF8.GetBytes(namePtr, name.Length, utf8Ptr, byteCount);
            }

            return vkGetInstanceProcAddr(_instance, utf8Ptr);
        }
```

![image](https://user-images.githubusercontent.com/661798/59639263-a39f9080-9152-11e9-9446-7fe912d76410.png)

It works fine for me in a regular C 32-bit program I tested with.

**Comment by SamVanheer** [comment]
That makes sense. The library developer has fixed the issue. Thanks for looking into this.
