### ISSUE TITLE
Unhandled IndexOutOfRangeException doing GetFrameInfo

### ISSUE THREAD

**Issue by baldurk** [baldurk/renderdoc#201]
I've seen a few crash dump uploads with this managed callstack. Unfortunately for managed crashes all I have to go on is the stacktrace as the minidump doesn't get anything useful.

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at renderdocui.Code.Core.<>c__DisplayClass6.b__3(ReplayRenderer r) in Core.cs:482
   at renderdocui.Code.RenderManager.RunThread() in RenderManager.cs:237
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

See [Core.cs:482 on v0.26](https://github.com/baldurk/renderdoc/blob/v0.26/renderdocui/Code/Core.cs#L482)

I'm not sure what to make of it - maybe the frameinfo array is empty somehow but I don't know how you'd have a capture without any frame data in it.

This issue just filed here in the hopes that someone who runs into this crash sees it and can give me more information :).

**Comment by baldurk** [comment]
I'm fairly sure now this is caused by mismatching updates between the core dll and the UI - see #264. That can cause the marshalling to break between the two parts and that would explain why the frame record could be empty.

As with #264 this has been fixed for the next version, so hopefully this will eventually go away.
