### ISSUE TITLE
Crash when replaying capture of ANGLE-on-Vulkan tests on Linux

### ISSUE THREAD

**Issue by ShabbyX** [baldurk/renderdoc#2039]
## Description

With #2022 fixed, I can successfully capture tests running through ANGLE-on-Vulkan. However, trying to replay any frame causes a segmentation fault.

Running through gdb, I see the following stack trace on segfault:

```
#0  0x00007ffff3f07688 in bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*) () at /home/<removed>/renderdoc/build2/bin/../lib/librenderdoc.so
#1  0x00007ffff3b6e668 in WrappedVulkan::ProcessChunk(ReadSerialiser&, VulkanChunk) () at /home/<removed>/renderdoc/build2/bin/../lib/librenderdoc.so
#2  0x00007ffff3b78f88 in WrappedVulkan::ContextReplayLog(CaptureState, unsigned int, unsigned int, bool) () at /home/<removed>/renderdoc/build2/bin/../lib/librenderdoc.so
#3  0x00007ffff3b7c691 in WrappedVulkan::ReadLogInitialisation(RDCFile*, bool) () at /home/<removed>/renderdoc/build2/bin/../lib/librenderdoc.so
#4  0x00007ffff443ac0c in ReplayController::PostCreateInit(IReplayDriver*, RDCFile*) () at /home/<removed>/renderdoc/build2/bin/../lib/librenderdoc.so
#5  0x00007ffff443c2b8 in ReplayController::CreateDevice(RDCFile*, ReplayOptions const&) () at /home/<removed>/renderdoc/build2/bin/../lib/librenderdoc.so
#6  0x00007ffff440e52e in CaptureFile::OpenCapture(ReplayOptions const&, std::function<void (float)>) () at /home/<removed>/renderdoc/build2/bin/../lib/librenderdoc.so
#7  0x0000555555bd1d97 in ReplayManager::run(int, QString const&, ReplayOptions const&, std::function<void (float)>) ()
#8  0x0000555555bd1f67 in std::_Function_handler<void (), ReplayManager::OpenCapture(QString const&, ReplayOptions const&, std::function<void (float)>)::{lambda()#1}>::_M_invoke(std::_Any_data const&)
    ()
#9  0x0000555555bd1ff1 in LambdaThread::process() ()
#10 0x00007ffff2976458 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff27805ae in QThread::started(QThread::QPrivateSignal) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff27829ba in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff2622609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#14 0x00007ffff21fc103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

The offending instruction is `mov    0x8,%rax`, and `info reg` shows `%rax` is 0. Context:

```
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2446>          je     0x7ffff3f0766c <bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2460>
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2448>          xor    %edx,%edx
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2450>          mov    $0x1,%esi
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2455>          callq  0x7ffff45c3a40 <Atomic::CmpExch32(int volatile*, int, int)>
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2460>          addq   $0xc8,-0x270(%rbp)
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2471>          mov    -0x200(%rbp),%rax
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2478>          jmpq   0x7ffff3f07490 <bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+1984>
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2483>          nopl   0x0(%rax,%rax,1)
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2488>         >mov    0x8,%rax
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2496>          ud2
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2498>          nopw   0x0(%rax,%rax,1)
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2504>          mov    -0x180(%rbp),%rdi
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2511>          callq  0x7ffff3ad9e60 <free@plt>
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2516>          jmpq   0x7ffff3f0707c <bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+940>
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2521>          nopl   0x0(%rax)
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2528>          mov    -0x1e0(%rbp),%rdi
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2535>          callq  0x7ffff3ad9e60 <free@plt>
<bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+2540>          jmpq   0x7ffff3f070d1 <bool WrappedVulkan::Serialise_vkEndCommandBuffer<ReadSerialiser>(ReadSerialiser&, VkCommandBuffer_T*)+1025>
```

## Steps to reproduce

- Download and build ANGLE
- Build renderdoc on Linux according to the instructions in #2022
- Run `./qrenderdoc`
- Use `<path/to/angle/build>/angle_end2end_tests` as Executable Path
- Use `--gtest_filter=MultisampledRenderToTextureES3Test.BlitFramebufferTest/ES3_Vulkan` as command line arguments
- Enable "Queue Capture" from "Frame 0", with "# Frames" 10
- Observe the crash during replay after successful capture

## Environment

* RenderDoc version: 31b81ade3
* Operating System: Linux (Ubuntu 20.04)
* Graphics API: Vulkan
* cmake arguments: -DCMAKE_BUILD_TYPE=Release -Bbuild -H. -DENABLE_GLES=OFF -DENABLE_GL=OFF
* GPU: NVIDIA GTX 970, driver 440.100

**Comment by ShabbyX** [comment]
Here's a saved capture: https://drive.google.com/file/d/17J7YWCIM5Z8R3A_G3CqYRWfIDOegaBD7

**Comment by baldurk** [comment]
This was a bug in the new command buffer allocator, that would free serialised commands after a command buffer reset even though during a capture if a command buffer is reset and recorded multiple times we need to store the commands for each 'version' for serialising to disk. That commit should fix the problem.
