### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by zmike** [baldurk/renderdoc#2178]
## Description
I installed renderdoc and all renderdoc executables crash on startup

## Steps to reproduce
Run any renderdoc executable

## Environment
Fedora 33, x86_64:
```
$ rpm -qi renderdoc
Name        : renderdoc
Version     : 1.8
Release     : 4.fc33
Architecture: x86_64
Install Date: Tue 16 Feb 2021 01:44:10 PM EST
Group       : Unspecified
Size        : 29079355
License     : MIT
Signature   : RSA/SHA256, Fri 07 Aug 2020 08:41:14 AM EDT, Key ID 49fd77499570ff31
Source RPM  : renderdoc-1.8-4.fc33.src.rpm
Build Date  : Fri 07 Aug 2020 08:27:23 AM EDT
Build Host  : buildvm-x86-09.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://renderdoc.org
Bug URL     : https://bugz.fedoraproject.org/renderdoc
Summary     : A stand-alone graphics debugging tool
Description :
A free MIT licensed stand-alone graphics debugger that allows quick
and easy single-frame capture and detailed introspection of any
application using Vulkan, OpenGL.
```

* RenderDoc version: 1.8
* Operating System: Fedora 33
* Graphics API: Any

backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6e88784 in rdcarray<SDObject*>::size (this=<optimized out>, this=<optimized out>) at /usr/src/debug/renderdoc-1.8-4.fc33.x86_64/renderdoc/api/replay/rdcarray.h:195
195	  size_t size() const { return usedCount; }
(gdb) bt
#0  0x00007ffff6e88784 in rdcarray<SDObject*>::size (this=<optimized out>, this=<optimized out>) at /usr/src/debug/renderdoc-1.8-4.fc33.x86_64/renderdoc/api/replay/rdcarray.h:195
#1  SDObject::NumChildren (this=<optimized out>) at /usr/src/debug/renderdoc-1.8-4.fc33.x86_64/renderdoc/api/replay/structured_data.h:488
#2  MergeConfigValues (prefix=..., dstConfig=0x0, srcConfig=0x10d94b0, updateDescs=false) at /usr/src/debug/renderdoc-1.8-4.fc33.x86_64/renderdoc/core/settings.cpp:274
#3  0x00007ffff6e85c69 in RenderDoc::ProcessConfig (this=0x7ffff7c46680 <_ZZN9RenderDoc4InstEvE8realInst.lto_priv.0>) at /usr/src/debug/renderdoc-1.8-4.fc33.x86_64/renderdoc/core/settings.cpp:471
#4  RenderDoc::Initialise (this=0x7ffff7c46680 <_ZZN9RenderDoc4InstEvE8realInst.lto_priv.0>) at /usr/src/debug/renderdoc-1.8-4.fc33.x86_64/renderdoc/core/core.cpp:458
#5  0x00007ffff6e8f0d1 in _sub_I_65535_0.0 () from /usr/bin/../lib64/renderdoc/librenderdoc.so
#6  0x00007ffff7fe18de in call_init.part () from /lib64/ld-linux-x86-64.so.2
#7  0x00007ffff7fe19c8 in _dl_init () from /lib64/ld-linux-x86-64.so.2
#8  0x00007ffff7fd20ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#9  0x0000000000000001 in ?? ()
#10 0x00007fffffffe082 in ?? ()
#11 0x0000000000000000 in ?? ()
```

Additional debug info:
```
(gdb) fr 3
#3  0x00007ffff6e85c69 in RenderDoc::ProcessConfig (this=0x7ffff7c46680 <_ZZN9RenderDoc4InstEvE8realInst.lto_priv.0>) at /usr/src/debug/renderdoc-1.8-4.fc33.x86_64/renderdoc/core/settings.cpp:471
471	  bool outofDate = ::MergeConfigValues(rdcstr(), m_Config, loadedConfig, false);
(gdb) p m_Config
$1 = (SDObject *) 0x0
```

Happy to provide any further info or debugging as is useful.

**Comment by zmike** [comment]
Fixed by building newer version from source.
