### ISSUE TITLE
EGL hook issue

### ISSUE THREAD

**Issue by spencercw** [baldurk/renderdoc#2494]
## Description

The application I am running through RenderDoc crashes when invoking `eglSwapBuffersWithDamageKHR` (stack trace below). I've had a poke around the RenderDoc code and I think this is happening because, at least on my system, libEGL.so does not export this symbol. When the application invokes `eglGetProcAddress("eglSwapBuffersWithDamageKHR")` normally, it receives a function pointer inside libEGL_mesa.so, although this library does not directly export any useful symbols itself.

```
#0  0x0000000000000000 in ?? ()
#1  0x00007fb02716859b in eglSwapBuffersWithDamageKHR_renderdoc_hooked (dpy=0x7fb00c000bd0, surface=0x7fb00c1350a0, rects=0x7fb016512780, n_rects=1) at /home/chris/projects/renderdoc/renderdoc/driver/gl/egl_hooks.cpp:636
#2  0x000055b546073886 in swapWithDamage (data=0x55b5463e72d0 <data>, display=0x7fb00c000bd0, surface=0x7fb00c1350a0, damage=0x7fb0165137e0, count=1) at /home/chris/projects/LookingGlass/client/src/eglutil.c:72
#3  0x000055b5461689fc in x11EGLSwapBuffers (display=0x7fb00c000bd0, surface=0x7fb00c1350a0, damage=0x7fb0165137e0, count=1) at /home/chris/projects/LookingGlass/client/displayservers/X11/x11.c:1425
#4  0x000055b546068fd2 in app_eglSwapBuffers (display=0x7fb00c000bd0, surface=0x7fb00c1350a0, damage=0x7fb0165137e0, count=1) at /home/chris/projects/LookingGlass/client/src/app.c:596
#5  0x000055b5461761e8 in egl_render (renderer=0x55b5482fd010, rotate=LG_ROTATE_0, newFrame=false, invalidateWindow=false, preSwap=0x55b546052552 <preSwapCallback>, udata=0x7fb016513d00) at /home/chris/projects/LookingGlass/client/renderers/EGL/egl.c:1202
#6  0x000055b546053661 in renderThread (unused=0x0) at /home/chris/projects/LookingGlass/client/src/main.c:283
#7  0x000055b5461a3672 in threadWrapper (opaque=0x55b5483a52e0) at /home/chris/projects/LookingGlass/common/src/platform/linux/thread.c:40
#8  0x00007fb026504259 in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007fb0260635e3 in clone () from /usr/lib/libc.so.6
```

```
$ nm -gD /usr/lib/libEGL.so
                 U abort@GLIBC_2.2.5
                 U __assert_fail@GLIBC_2.2.5
                 U calloc@GLIBC_2.2.5
                 U __ctype_tolower_loc@GLIBC_2.3
                 w __cxa_finalize@GLIBC_2.2.5
                 U dladdr@GLIBC_2.2.5
                 U dlclose@GLIBC_2.2.5
                 U dlopen@GLIBC_2.2.5
                 U dlsym@GLIBC_2.2.5
0000000000007020 T eglBindAPI
0000000000007f60 T eglBindTexImage
0000000000007ef0 T eglChooseConfig
0000000000007fc0 T eglClientWaitSync
0000000000008030 T eglCopyBuffers
0000000000008090 T eglCreateContext
0000000000008100 T eglCreateImage
0000000000008170 T eglCreatePbufferFromClientBuffer
00000000000081e0 T eglCreatePbufferSurface
0000000000008240 T eglCreatePixmapSurface
00000000000082b0 T eglCreatePlatformPixmapSurface
0000000000008390 T eglCreatePlatformWindowSurface
0000000000008470 T eglCreateSync
00000000000084d0 T eglCreateWindowSurface
0000000000008540 T eglDestroyContext
00000000000085a0 T eglDestroyImage
0000000000008600 T eglDestroySurface
0000000000008660 T eglDestroySync
00000000000086c0 T eglGetConfigAttrib
0000000000008730 T eglGetConfigs
00000000000063c0 T eglGetCurrentContext
0000000000006360 T eglGetCurrentDisplay
0000000000007150 T eglGetCurrentSurface
00000000000069f0 T eglGetDisplay
0000000000006410 T eglGetError
0000000000006e10 T eglGetPlatformDisplay
0000000000009ac0 T eglGetProcAddress
00000000000087a0 T eglGetSyncAttrib
0000000000008810 T eglInitialize
0000000000007200 T eglMakeCurrent
0000000000006310 T eglQueryAPI
0000000000008870 T eglQueryContext
00000000000095f0 T eglQueryString
00000000000088e0 T eglQuerySurface
0000000000008950 T eglReleaseTexImage
0000000000004de0 T eglReleaseThread
00000000000089b0 T eglSurfaceAttrib
0000000000008a20 T eglSwapBuffers
0000000000008a80 T eglSwapInterval
0000000000008ae0 T eglTerminate
0000000000008b70 T eglWaitClient
0000000000008bc0 T eglWaitGL
0000000000008b30 T eglWaitNative
0000000000008c10 T eglWaitSync
                 U exit@GLIBC_2.2.5
                 U fclose@GLIBC_2.2.5
                 U fileno@GLIBC_2.2.5
                 U fnmatch@GLIBC_2.2.5
                 U fopen64@GLIBC_2.2.5
                 U fread@GLIBC_2.2.5
                 U free@GLIBC_2.2.5
                 U fstat64@GLIBC_2.33
                 U fwrite@GLIBC_2.2.5
                 U getegid@GLIBC_2.2.5
                 U getenv@GLIBC_2.2.5
                 U geteuid@GLIBC_2.2.5
                 U getgid@GLIBC_2.2.5
                 U getpagesize@GLIBC_2.2.5
                 U getpid@GLIBC_2.2.5
                 U getuid@GLIBC_2.2.5
                 U __glDispatchCheckMultithreaded
                 U __glDispatchCreateTable
                 U __glDispatchDestroyTable
                 U __glDispatchFini
                 U __glDispatchForceUnpatch
                 U __glDispatchGetABIVersion
                 U __glDispatchGetCurrentThreadState
                 U __glDispatchGetProcAddress
                 U __glDispatchInit
                 U __glDispatchLoseCurrent
                 U __glDispatchMakeCurrent
                 U __glDispatchNewVendorID
                 U __glDispatchReset
                 w __gmon_start__
                 U __isoc99_sscanf@GLIBC_2.7
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 U localeconv@GLIBC_2.2.5
                 U malloc@GLIBC_2.2.5
                 U memcmp@GLIBC_2.2.5
                 U memcpy@GLIBC_2.14
                 U memmove@GLIBC_2.2.5
                 U mincore@GLIBC_2.2.5
                 U realloc@GLIBC_2.2.5
                 U realpath@GLIBC_2.3
                 U scandir64@GLIBC_2.2.5
                 U sched_yield@GLIBC_2.2.5
                 U __snprintf_chk@GLIBC_2.3.4
                 U __stack_chk_fail@GLIBC_2.4
                 U stderr@GLIBC_2.2.5
                 U strchr@GLIBC_2.2.5
                 U strcmp@GLIBC_2.2.5
                 U strdup@GLIBC_2.2.5
                 U strlen@GLIBC_2.2.5
                 U strncmp@GLIBC_2.2.5
                 U strrchr@GLIBC_2.2.5
                 U strtod@GLIBC_2.2.5
                 U strtol@GLIBC_2.2.5
                 U __vsnprintf_chk@GLIBC_2.3.4
```

```
$ nm -gD /usr/lib/libEGL_mesa.so
                 U abort@GLIBC_2.2.5
                 U alphasort64@GLIBC_2.2.5
                 U __asprintf_chk@GLIBC_2.8
                 U calloc@GLIBC_2.2.5
                 U clock_gettime@GLIBC_2.17
                 U close@GLIBC_2.2.5
                 U __cxa_atexit@GLIBC_2.2.5
                 w __cxa_finalize@GLIBC_2.2.5
                 U dlclose@GLIBC_2.2.5
                 U dlerror@GLIBC_2.2.5
                 U dlopen@GLIBC_2.2.5
                 U dlsym@GLIBC_2.2.5
                 U drmAuthMagic
                 U drmCommandWriteRead
                 U drmDevicesEqual
                 U drmFreeDevice
                 U drmFreeDevices
                 U drmFreeVersion
                 U drmGetCap
                 U drmGetDevice2
                 U drmGetDeviceNameFromFd2
                 U drmGetDevices2
                 U drmGetMagic
                 U drmGetNodeTypeFromFd
                 U drmGetRenderDeviceNameFromFd
                 U drmGetVersion
                 U drmIoctl
000000000002aa10 T __egl_Main
                 U __errno_location@GLIBC_2.2.5
                 U exit@GLIBC_2.2.5
                 U fcntl64@GLIBC_2.28
                 U __fprintf_chk@GLIBC_2.3.4
                 U free@GLIBC_2.2.5
                 U fstat64@GLIBC_2.33
                 U ftruncate64@GLIBC_2.2.5
                 U gbm_bo_create
                 U gbm_bo_create_with_modifiers
                 U gbm_bo_destroy
                 U gbm_bo_get_bpp
                 U gbm_create_device
                 U gbm_device_destroy
                 U gbm_device_get_backend_name
                 U gbm_device_get_fd
                 U gbm_format_get_name
                 U getenv@GLIBC_2.2.5
                 U geteuid@GLIBC_2.2.5
                 U getuid@GLIBC_2.2.5
                 U _glapi_get_proc_address
                 w __gmon_start__
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 U malloc@GLIBC_2.2.5
                 U memcmp@GLIBC_2.2.5
                 U memcpy@GLIBC_2.14
                 U __memcpy_chk@GLIBC_2.3.4
                 U memfd_create@GLIBC_2.27
                 U memset@GLIBC_2.2.5
                 U mincore@GLIBC_2.2.5
                 U mmap64@GLIBC_2.2.5
                 U munmap@GLIBC_2.2.5
                 U open64@GLIBC_2.2.5
                 U __popcountdi2@GCC_3.4
                 U pow@GLIBC_2.29
                 U __progname_full@GLIBC_2.2.5
                 U program_invocation_name@GLIBC_2.2.5
                 U pthread_condattr_init@GLIBC_2.2.5
                 U pthread_condattr_setclock@GLIBC_2.3.3
                 U pthread_cond_broadcast@GLIBC_2.3.2
                 U pthread_cond_destroy@GLIBC_2.3.2
                 U pthread_cond_init@GLIBC_2.3.2
                 U pthread_cond_timedwait@GLIBC_2.3.2
                 U pthread_cond_wait@GLIBC_2.3.2
                 U pthread_key_create@GLIBC_2.2.5
                 U pthread_key_delete@GLIBC_2.2.5
                 U pthread_mutex_destroy@GLIBC_2.2.5
                 U pthread_mutex_init@GLIBC_2.2.5
                 U pthread_mutex_lock@GLIBC_2.2.5
                 U pthread_mutex_unlock@GLIBC_2.2.5
                 U pthread_setspecific@GLIBC_2.2.5
                 U read@GLIBC_2.2.5
                 U readlink@GLIBC_2.2.5
                 U realloc@GLIBC_2.2.5
                 U realpath@GLIBC_2.3
                 U regcomp@GLIBC_2.2.5
                 U regexec@GLIBC_2.3.4
                 U regfree@GLIBC_2.2.5
                 U scandir64@GLIBC_2.2.5
                 U __snprintf_chk@GLIBC_2.3.4
                 U __stack_chk_fail@GLIBC_2.4
                 U stderr@GLIBC_2.2.5
                 U strcasecmp@GLIBC_2.2.5
                 U strchr@GLIBC_2.2.5
                 U strcmp@GLIBC_2.2.5
                 U strdup@GLIBC_2.2.5
                 U strerror@GLIBC_2.2.5
                 U strlen@GLIBC_2.2.5
                 U strncmp@GLIBC_2.2.5
                 U strndup@GLIBC_2.2.5
                 U strrchr@GLIBC_2.2.5
                 U strspn@GLIBC_2.2.5
                 U strstr@GLIBC_2.2.5
                 U sysconf@GLIBC_2.2.5
                 U __vasprintf_chk@GLIBC_2.8
                 U __vfprintf_chk@GLIBC_2.3.4
                 U __vsnprintf_chk@GLIBC_2.3.4
                 U wl_buffer_interface
                 U wl_callback_interface
                 U wl_client_post_no_memory
                 U wl_display_connect
                 U wl_display_create_queue
                 U wl_display_disconnect
                 U wl_display_dispatch_pending
                 U wl_display_dispatch_queue
                 U wl_display_dispatch_queue_pending
                 U wl_display_flush
                 U wl_display_interface
                 U wl_display_roundtrip_queue
                 U wl_event_queue_destroy
                 U wl_global_create
                 U wl_global_destroy
                 U wl_proxy_add_listener
                 U wl_proxy_create_wrapper
                 U wl_proxy_destroy
                 U wl_proxy_get_version
                 U wl_proxy_marshal_flags
                 U wl_proxy_set_queue
                 U wl_proxy_wrapper_destroy
                 U wl_registry_interface
                 U wl_resource_create
                 U wl_resource_destroy
                 U wl_resource_get_user_data
                 U wl_resource_instance_of
                 U wl_resource_post_error
                 U wl_resource_post_event
                 U wl_resource_post_no_memory
                 U wl_resource_set_implementation
                 U wl_shm_interface
                 U wl_shm_pool_interface
                 U wl_surface_interface
                 U xcb_change_property_checked
                 U xcb_connect
                 U xcb_connection_has_error
                 U xcb_copy_area
                 U xcb_copy_area_checked
                 U xcb_create_gc
                 U xcb_create_pixmap
                 U xcb_delete_property_checked
                 U xcb_depth_next
                 U xcb_depth_visuals
                 U xcb_depth_visuals_iterator
                 U xcb_depth_visuals_length
                 U xcb_discard_reply
                 U xcb_disconnect
                 U xcb_dri2_authenticate_reply
                 U xcb_dri2_authenticate_unchecked
                 U xcb_dri2_connect_device_name
                 U xcb_dri2_connect_device_name_length
                 U xcb_dri2_connect_driver_name
                 U xcb_dri2_connect_driver_name_length
                 U xcb_dri2_connect_reply
                 U xcb_dri2_connect_unchecked
                 U xcb_dri2_copy_region_reply
                 U xcb_dri2_copy_region_unchecked
                 U xcb_dri2_create_drawable
                 U xcb_dri2_create_drawable_checked
                 U xcb_dri2_destroy_drawable
                 U xcb_dri2_get_buffers_buffers
                 U xcb_dri2_get_buffers_reply
                 U xcb_dri2_get_buffers_unchecked
                 U xcb_dri2_get_buffers_with_format_buffers
                 U xcb_dri2_get_buffers_with_format_reply
                 U xcb_dri2_get_buffers_with_format_unchecked
                 U xcb_dri2_get_msc
                 U xcb_dri2_get_msc_reply
                 U xcb_dri2_id
                 U xcb_dri2_query_version
                 U xcb_dri2_query_version_reply
                 U xcb_dri2_swap_buffers_reply
                 U xcb_dri2_swap_buffers_unchecked
                 U xcb_dri2_swap_interval
                 U xcb_dri3_buffer_from_pixmap
                 U xcb_dri3_buffer_from_pixmap_reply
                 U xcb_dri3_buffer_from_pixmap_reply_fds
                 U xcb_dri3_buffers_from_pixmap
                 U xcb_dri3_buffers_from_pixmap_offsets
                 U xcb_dri3_buffers_from_pixmap_reply
                 U xcb_dri3_buffers_from_pixmap_reply_fds
                 U xcb_dri3_buffers_from_pixmap_strides
                 U xcb_dri3_fence_from_fd
                 U xcb_dri3_get_supported_modifiers
                 U xcb_dri3_get_supported_modifiers_reply
                 U xcb_dri3_get_supported_modifiers_screen_modifiers
                 U xcb_dri3_get_supported_modifiers_window_modifiers
                 U xcb_dri3_id
                 U xcb_dri3_open
                 U xcb_dri3_open_reply
                 U xcb_dri3_open_reply_fds
                 U xcb_dri3_pixmap_from_buffer
                 U xcb_dri3_pixmap_from_buffers
                 U xcb_dri3_query_version
                 U xcb_dri3_query_version_reply
                 U xcb_flush
                 U xcb_free_gc
                 U xcb_free_pixmap
                 U xcb_generate_id
                 U xcb_get_extension_data
                 U xcb_get_geometry
                 U xcb_get_geometry_reply
                 U xcb_get_image
                 U xcb_get_image_data
                 U xcb_get_image_data_length
                 U xcb_get_image_reply
                 U xcb_get_setup
                 U xcb_intern_atom
                 U xcb_intern_atom_reply
                 U xcb_poll_for_special_event
                 U xcb_prefetch_extension_data
                 U xcb_present_id
                 U xcb_present_notify_msc
                 U xcb_present_pixmap
                 U xcb_present_query_capabilities
                 U xcb_present_query_capabilities_reply
                 U xcb_present_query_version
                 U xcb_present_query_version_reply
                 U xcb_present_select_input_checked
                 U xcb_put_image
                 U xcb_register_for_special_xge
                 U xcb_request_check
                 U xcb_screen_allowed_depths_iterator
                 U xcb_screen_next
                 U xcb_setup_roots_iterator
                 U xcb_sync_destroy_fence
                 U xcb_sync_trigger_fence
                 U xcb_unregister_for_special_event
                 U xcb_wait_for_special_event
                 U xcb_xfixes_create_region
                 U xcb_xfixes_destroy_region
                 U xcb_xfixes_id
                 U xcb_xfixes_query_version
                 U xcb_xfixes_query_version_reply
                 U xcb_xfixes_set_region
                 U XGetXCBConnection
                 U XML_ErrorString
                 U XML_GetBuffer
                 U XML_GetErrorCode
                 U XML_ParseBuffer
                 U XML_ParserCreate
                 U XML_ParserFree
                 U XML_SetElementHandler
                 U XML_SetUserData
                 U xshmfence_alloc_shm
                 U xshmfence_await
                 U xshmfence_map_shm
                 U xshmfence_reset
                 U xshmfence_trigger
                 U xshmfence_unmap_shm
```
## Steps to reproduce

1. Run an application which invokes `eglSwapBuffersWithDamageKHR` (I'm using [Looking Glass](https://looking-glass.io/)). Application crashes.

(Sorry this is not very useful. There's clearly something 'off' with my environment that is not meshing well with RenderDoc.)

## Environment

* RenderDoc version: 874134da (originally tested 1.18 which exhibited the same behaviour)
* Operating System: Manjaro Linux 21.2.3
* Graphics API: EGL
* GPU:  Intel UHD Graphics 770 (Core i7-12700K)
* Mesa version: 21.3.5
* libglvnd version (owns /usr/lib/libEGL.so): 1.4.0

**Comment by baldurk** [comment]
That commit is partly speculative. I was able to reconstruct a synthetic test based on your description but I wasn't able to run your original program to reproduce - I compiled it, but looking through it, it seems to require a complex VM hardware sharing setup which I can't replicate and I wasn't able to see a way to run it in a 'dummy' way to test the rendering.

If there's a way to test that properly let me know, otherwise if you're able to test that commit yourself and see if it addresses the problem that would be good to know.

**Comment by spencercw** [comment]
Yeah Looking Glass is quite complex to set up. I'm not sure there's an easy way for you to test it without having a virtual machine with GPU passthrough set up.

Anyway, I have tested it myself and can confirm the crash no longer occurs. Thanks for resolving.
