### ISSUE TITLE
Crash when capturing a frame in a Vulkan program calling vkFreeMemory

### ISSUE THREAD

**Issue by BinaryWarlock** [baldurk/renderdoc#2573]
## Description

My program renders a frame, and then cleans up some transient buffers after the frame has been rendered.

It looks roughly like this:
```c
VkBuffer buffer[N];
VkDeviceMemory memory[N];

// Create and map memories, create buffers bound to those memories, etc.

// Render frame using buffer/memory

// Wait for everything to be rendered and used
vkDeviceWaitIdle(device);

// At this point buffer/memory is unused, the queue has completed
for(int i = 0; i < N; i++) {
    vkDestroyBuffer(device, buffer[i], NULL);
    vkFreeMemory(device, memory[i], NULL);
}
```

The program works and passes Vulkan validation, but if I attempt to capture a frame in Renderdoc, the program segfaults.

The Renderdoc log shows:
```
Core 7108 16:25:55 target_control.cpp(859) Log   Used API: Vulkan (Not presenting & supported)
Core 7108 16:25:55 target_control.cpp(859) Log   Used API: Vulkan (Presenting & supported)
Core 7430 16:25:58 vk_core.cpp(1780)      Log   Starting capture
Core 7430 16:25:58 resource_manager.h(1441) Debug Preparing up to 281 potentially dirty resources
Core 7430 16:25:58 resource_manager.h(1494) Debug Prepared 135 dirty resources, postponed 131, skipped 0
Core 7430 16:25:58 vk_core.cpp(1852)      Debug Attempting capture
Core 7430 16:25:58 resource_manager.h(1124) Log   Preparing resource Unknown Resource 165290 after it has been postponed.
Core 7430 16:25:58 resource_manager.h(1124) Log   Preparing resource Unknown Resource 165305 after it has been postponed.
Core 7430 16:25:58 resource_manager.h(1124) Log   Preparing resource Unknown Resource 165320 after it has been postponed.
Core 7430 16:25:58 resource_manager.h(1124) Log   Preparing resource Unknown Resource 165348 after it has been postponed.
Core 7430 16:25:58 resource_manager.h(1124) Log   Preparing resource Unknown Resource 165359 after it has been postponed.
Core 7430 16:25:58 resource_manager.h(1124) Log   Preparing resource Unknown Resource 165336 after it has been postponed.
Core 7430 16:25:58 resource_manager.h(1124) Log   Preparing resource Unknown Resource 165382 after it has been postponed.
Core 7430 16:25:58 resource_manager.h(1124) Log   Preparing resource Unknown Resource 165393 after it has been postponed.
Core 7430 16:25:58 vk_core.cpp(4150)      Warning [VUID-vkCmdCopyBuffer-srcBuffer-parameter] Validation Error: [ VUID-vkCmdCopyBuffer-srcBuffer-parameter ] Object 0: handle = 0x5570aa78b4c0, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xf31f51da | Invalid VkBuffer Object 0x67fa550000025052. The Vulkan spec states: srcBuffer must be a valid VkBuffer handle (https://vulkan.lunarg.com/doc/view/1.3.204.1/linux/1.3-extensions/vkspec.html#VUID-vkCmdCopyBuffer-srcBuffer-parameter)
```

Which suggests it's attempting to prepare a postponed resource, and the backtrace of the program in gdb:

```
#0  CoreChecks::ValidateMemoryIsBoundToBuffer (this=this@entry=0x5570ab1a4400, buffer_state=0x0, 
    api_name=api_name@entry=0x7f26fb39e55c "vkCmdCopyBuffer", 
    error_code=error_code@entry=0x7f26fb49b350 "VUID-vkCmdCopyBuffer-srcBuffer-00119")
    at /vulkan-sdk/1.3.204.1/source/Vulkan-ValidationLayers/layers/core_validation.cpp:198
#1  0x00007f26fae2182a in CoreChecks::ValidateCmdCopyBuffer<VkBufferCopy> (this=0x5570ab1a4400, 
    commandBuffer=<optimized out>, srcBuffer=<optimized out>, dstBuffer=<optimized out>, regionCount=1, 
    pRegions=0x7ffcf0dbe520, cmd_type=CMD_COPYBUFFER)
    at /vulkan-sdk/1.3.204.1/source/Vulkan-ValidationLayers/layers/buffer_validation.cpp:6116
#2  0x00007f26fadfd32b in CoreChecks::PreCallValidateCmdCopyBuffer (this=<optimized out>, 
    commandBuffer=<optimized out>, srcBuffer=<optimized out>, dstBuffer=<optimized out>, 
    regionCount=<optimized out>, pRegions=<optimized out>)
    at /vulkan-sdk/1.3.204.1/source/Vulkan-ValidationLayers/layers/buffer_validation.cpp:6143
#3  0x00007f26fab7e379 in vulkan_layer_chassis::CmdCopyBuffer (commandBuffer=0x5570ade2bad0, 
    srcBuffer=0x67fa550000025052, dstBuffer=0xe5656a000002557d, regionCount=1, pRegions=0x7ffcf0dbe520)
    at /vulkan-sdk/1.3.204.1/source/Vulkan-ValidationLayers/layers/generated/chassis.cpp:3172
#4  0x00007f27407de90f in WrappedVulkan::Prepare_InitialState (this=0x5570aac053f0, res=0x5570a9bc25c0)
    at /home/user/code/renderdoc-1.19/renderdoc/driver/vulkan/vk_initstate.cpp:469
#5  0x00007f27407fe200 in VulkanResourceManager::Prepare_InitialState (this=0x5570a9be57f0, res=0x5570a9bc25c0)
    at /home/user/code/renderdoc-1.19/renderdoc/driver/vulkan/vk_manager.cpp:993
#6  0x00007f27406cbe1f in ResourceManager<VulkanResourceManagerConfiguration>::Prepare_InitialStateIfPostponed (
    this=0x5570a9be57f0, id=..., midframe=true)
    at /home/user/code/renderdoc-1.19/renderdoc/core/resource_manager.h:1127
#7  0x00007f27406ca730 in ResourceManager<VulkanResourceManagerConfiguration>::ReleaseCurrentResource (
    this=0x5570a9be57f0, id=...) at /home/user/code/renderdoc-1.19/renderdoc/core/resource_manager.h:1898
#8  0x00007f274078cd96 in VulkanResourceManager::ReleaseWrappedResource<VkDeviceMemory_T*> (this=0x5570a9be57f0, 
    obj=0x5570a9bc25c0, clearID=false) at /home/user/code/renderdoc-1.19/renderdoc/driver/vulkan/vk_manager.h:327
#9  0x00007f2740d9f1d8 in WrappedVulkan::vkFreeMemory (this=0x5570aac053f0, device=0x5570a9bc1270, 
    memory=0x5570a9bc25c0, pAllocator=0x0)
    at /home/user/code/renderdoc-1.19/renderdoc/driver/vulkan/wrappers/vk_resource_funcs.cpp:753
#10 0x00007f2740c0bf0b in hooked_vkFreeMemory (device=0x5570a9bc1270, mem=0x5570a9bc25c0, pAllocator=0x0)
    at /home/user/code/renderdoc-1.19/renderdoc/driver/vulkan/vk_layer.cpp:243
```

As you can see, the crash results from the `vkFreeMemory` call, and and as it ends up being a postponed resource, it calls into `WrappedVulkan::Prepare_InitialState`:

```c++
    ObjDisp(d)->CmdCopyBuffer(Unwrap(cmd), Unwrap(record->memMapState->wholeMemBuf), Unwrap(dstBuf),
                              1, &region);
```

The problem here is that srcBuf is invalid, for whatever reason. We can see a bogus pointer:
```
#3  0x00007f26fab7e379 in vulkan_layer_chassis::CmdCopyBuffer (commandBuffer=0x5570ade2bad0, 
    srcBuffer=0x67fa550000025052, dstBuffer=0xe5656a000002557d, regionCount=1, pRegions=0x7ffcf0dbe520)
```

(FWIW, dstBuffer there also seems to be bogus, but I'm not sure why that would be?)

This causes validation (of RenderDoc) to fail and the consumer to segfault. 
If validation layers are disabled, it crashes in the driver instead, in a memcpy (because the pointers are bogus).

Without capturing, the freeing works fine and never crashes.

On a whim I also tried swapping the vkFreeMemory and vkFreeBuffer calls, that changed nothing.

If I remove the calls to vkFreeMemory and vkFreeBuffer, the capture succeeds without segfaulting.

## Steps to reproduce

Unfortunately I'm not sure how to provide a reproducible test case for this, because I cannot share my program (parts of it are proprietary, and the data necessary to run it is too large), and I'm not sure how to minimize it given the state depends on a lot of things.

## Environment

* RenderDoc version: 1.19 as well as the current latest commit (4953adde03c18843adc94cd3921e2e545f70df5a)
* Operating System: Linux
* Graphics API: Vulkan 1.1

**Comment by baldurk** [comment]
Sorry for the delay in getting to this. I wasn't able to reproduce the error you were seeing exactly, and I'm not quite sure how it happened. I did find the bug, the buffer used for memory copies was freed too soon before being used to readback the memory contents when memory is freed mid-capture like this. But in my case it always manifested as an invalid degenerate copy, because the destination buffer was allocated and re-used the freed buffer's handle.

I didn't dig in further since maybe there's some information missing from your description that slightly changes the codepath, and I was still able to reproduce the likely bug. Let me know if that doesn't fix the problem.
