### ISSUE TITLE
My app crashes after renderdoc

### ISSUE THREAD

**Issue by klaxons1** [baldurk/renderdoc#2577]
After running renderdoc via adb, I cannot open my app , 
It's crashing with following log :

java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.ApplicationInfo.primaryCpuAbi' on a null object reference
	at android.os.GraphicsEnvironment.chooseAbi(GraphicsEnvironment.java:888)
	at android.os.GraphicsEnvironment.getDebugLayerAppPaths(GraphicsEnvironment.java:253)
	at android.os.GraphicsEnvironment.getDebugLayerPathsFromSettings(GraphicsEnvironment.java:227)
	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:843)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:960)
	at android.app.LoadedApk.getResources(LoadedApk.java:1192)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2671)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6846)
	at android.app.ActivityThread.access$1500(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by baldurk** [comment]
Hi there, your issue has been closed due to not correctly following the issue template. Please [read the documentation about filing issues](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) and open a new issue which does follow the issue template. Do not reply to this issue with more information or with a correctly formatted issue, as that will only lead to confusion.

I try to address all github issues and fix bugs quickly, but badly formatted issues or poorly described bug reports especially are a significant drain on project resources. Taking a few minutes to file a good issue makes a huge difference and will get it addressed faster - everybody wins!

In github when you first create a new issue the form is pre-populated with a template which you should read over and follow. As linked above there is [documentation](https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Filing-Issues.md) going into more detail about what makes a good issue.
