### ISSUE TITLE
Segmentation fault debugging a Vulkan app

### ISSUE THREAD

**Issue by melody-rs** [baldurk/renderdoc#2939]
## Description
I'm trying to debug [my app using wgpu](https://github.com/Astrabit-ST/Luminol) and when taking a capture and attempting to view it, renderdoc segfaults. 

## Steps to reproduce

- Compile Luminol
- Open a project and open a map
- Take a capture
- Open the capture
- Renderdoc will show a loading bar, hang, and crash

Here's a capture that renderdoc segfaults on when trying to open:
[luminol-renderdoc-segfault.zip](https://github.com/baldurk/renderdoc/files/11479823/luminol-renderdoc-segfault.zip)
(Zipped cause github doesn't like rdc files)

If you need a sample project or luminol, I'd be happy to send it your way!

## Environment

* RenderDoc version: 1.25
* Operating System: Manjaro Linux (Running Linux Kernel 6.1.26)
* Graphics API: Vulkan

## Hardware
CPU: Intel i7-4980HQ @ 4 GHz 
GPU: Intel Crystal Well 
Host: MacBookPro11,4 1.0 (i have no idea what model mine is but its fairly old)

**Comment by baldurk** [comment]
I can't reproduce this unfortunately. I don't have any GPUs that precisely match yours, but on my NV GPU if I remap the memory allocations to be compatible with its requirements the capture loads fine. Similarly on my Intel Xe with latest mesa if I change the memory type index to point to a compatible device local/host visible memory type it also loads correctly.

In your description you say you're running v1.25. I'm not sure if there's any reason why you're running an old version but can you please test this with v1.26, and ideally with latest code as well?

If that doesn't make any difference, are you able to try testing with a different GPU to see if the problem is localised to your device?

One thing I notice is that you have memory mapped with optimal-tiled resources bound to it. This is easy to do on a system with only one memory type but I would strongly recommend not mapping memory allocations used for optimal resources anyway as it will cause performance degradation in RenderDoc at the very least if not correctness problems. If you could test your program without binding any tiled resources to memory that you're going to map, that would also be useful.

**Comment by baldurk** [comment]
Closing this due to lack of activity from the reporter and no further information to investigate.

If you are the reporter and this bug is still a problem for you, or you are someone finding this issue and you believe this bug is still a problem and you have more information to share, please do not comment here and instead please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents confusion of accidentally linking two unrelated bugs and means that each issue can be handled in a clean process.

**Comment by Kurapikov** [comment]
Hay baldurk, 
I am debugging my application under vmware workstation 17.0, Ubuntu 23.04 and my application uses Vulkan API. RenderDoc version is 1.29 Linux. The phenomenal is exactly same as @Speak2Erase described. I think maybe this environment is easier to reproduce?

bt of gdb shows:
`
#0  0x00007ff355a003f2 in fill_sampler_stage (state=0x1801200, dyn_info=<optimized out>, 
    stage=stage@entry=MESA_SHADER_VERTEX, p_stage=MESA_SHADER_VERTEX, array_idx=array_idx@entry=0, 
    descriptor=0x266d420, binding=0x30418b0) at ../src/gallium/frontends/lavapipe/lvp_execute.c:1123
#1  0x00007ff355a01ed4 in handle_descriptor (state=state@entry=0x1801200, dyn_info=dyn_info@entry=0x7ff349ffcb50, 
    binding=binding@entry=0x30418b0, stage=stage@entry=MESA_SHADER_VERTEX, 
    p_stage=p_stage@entry=MESA_SHADER_VERTEX, array_idx=array_idx@entry=0, type=<optimized out>, 
    descriptor=0x266d420) at ../src/gallium/frontends/lavapipe/lvp_execute.c:1242
#2  0x00007ff355a02004 in handle_set_stage (state=state@entry=0x1801200, dyn_info=dyn_info@entry=0x7ff349ffcb50, 
    set=set@entry=0x266d240, stage=stage@entry=MESA_SHADER_VERTEX, p_stage=p_stage@entry=MESA_SHADER_VERTEX)
    at ../src/gallium/frontends/lavapipe/lvp_execute.c:1275
#3  0x00007ff355a02194 in handle_descriptor_sets (cmd=cmd@entry=0x6721570, state=state@entry=0x1801200)
    at ../src/gallium/frontends/lavapipe/lvp_execute.c:1357
#4  0x00007ff355a05b35 in lvp_execute_cmd_buffer (cmd_buffer=<optimized out>, state=state@entry=0x1801200)
    at ../src/gallium/frontends/lavapipe/lvp_execute.c:4049
#5  0x00007ff355a09a85 in lvp_execute_cmds (device=0x17ffec0, queue=queue@entry=0x1800ff8, 
    cmd_buffer=<optimized out>) at ../src/gallium/frontends/lavapipe/lvp_execute.c:4347
#6  0x00007ff3559fbcb6 in lvp_queue_submit (submit=<optimized out>, vk_queue=<optimized out>)
    at ../src/gallium/frontends/lavapipe/lvp_device.c:1521
#7  lvp_queue_submit (vk_queue=0x1800ff8, submit=0x4a35670) at ../src/gallium/frontends/lavapipe/lvp_device.c:1506
#8  0x00007ff3558d78f6 in vk_queue_submit_final (queue=queue@entry=0x1800ff8, submit=submit@entry=0x4a35670)
    at ../src/vulkan/runtime/vk_queue.c:377
#9  0x00007ff3558d7b78 in vk_queue_submit_thread_func (_data=_data@entry=0x1800ff8)
    at ../src/vulkan/runtime/vk_queue.c:490
#10 0x00007ff3558c996b in impl_thrd_routine (p=<optimized out>) at ../src/c11/impl/threads_posix.c:67
#11 0x00007ff35768f6ba in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#12 0x00007ff35771e0d0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
`

**Comment by baldurk** [comment]
Please do not comment on old issues that have been closed.

If you are encountering a bug or are requesting a feature please open [a new issue](https://github.com/baldurk/renderdoc/issues/new/choose). You can reference this issue if you wish, but opening a new issue prevents any confusion of accidentally linking two unrelated issues and means that each issue can be handled in a clean process.
