### ISSUE TITLE
RenderDoc cannot target python OpenGL on linux

### ISSUE THREAD

**Issue by rspencer01** [baldurk/renderdoc#584]
Given the minimum not-working example,
``` python
import OpenGL.GL as gl
import OpenGL.GLU as glu
import OpenGL.GLUT as glut

glut.glutInit()
glut.glutInitContextVersion(4, 2);
glut.glutInitContextFlags(glut.GLUT_FORWARD_COMPATIBLE);
glut.glutInitContextProfile(glut.GLUT_CORE_PROFILE);
glut.glutInitDisplayMode(glut.GLUT_DOUBLE | glut.GLUT_RGBA | glut.GLUT_DEPTH)
glut.glutInitWindowSize(512,512);
glut.glutCreateWindow("Test")
glut.glutMainLoop()
```
saved as a python file, the command 
```
bin/renderdoccmd capture python /tmp/t.py 
```
fails with
```
Launching 'python' with params: /tmp/t.py
Log     - Loading into /usr/bin/python2.7
Traceback (most recent call last):
  File "/tmp/t.py", line 1, in <module>
    import OpenGL.GL as gl
  File "/usr/lib/python2.7/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python2.7/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python2.7/dist-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/platform/__init__.py", line 26, in _load
    plugin_class = plugin.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/platform/glx.py", line 5, in <module>
    class GLXPlatform( baseplatform.BasePlatform ):
  File "/usr/lib/python2.7/dist-packages/OpenGL/platform/glx.py", line 17, in GLXPlatform
    raise ImportError("Unable to load OpenGL library", *err.args)
ImportError: ('Unable to load OpenGL library', 'GL: cannot open shared object file: No such file or directory', 'GL', None)
Launched as ID 38920
```
on Ubuntu 14.04.

Version info:
```
renderdoccmd x64 0.33-efc592bfe6dc0dfcfe7dc53135f5a6e0f1cdae5c
APIs supported at compile-time: Vulkan, GL.
Windowing systems supported at compile-time: xlib, XCB, Vulkan KHR_display.
```

**Comment by baldurk** [comment]
Hey, I had a very quick look at this just now, and I seem to get some strange behaviour. I'm not familiar with python really, but if I run the test script with python3 on v0.33 everything works fine. Only if I run it with python2 then I get the error you are seeing.

I tried on the latest code, and it seems like it works there on python2 or python3. I'm not sure what would have changed since v0.33 in that respect but there have been some changes to the GL hooking to accommodate EGL. I don't really know what the error actually means and the code wasn't very clear, so I don't know what might have fixed it incidentally.

Can you build from latest code and try again to see if it works for you? I can look in more detail tomorrow if need be.

**Comment by baldurk** [comment]
As far as I can see this sample is still working on python2 and python3 in v0.34, so I'm going to close this issue. If you're still having trouble feel free to comment with more information.
