### ISSUE TITLE
RenderDoc trips assertion during replay of vkDebugMarkerSetObjectNameEXT

### ISSUE THREAD

**Issue by Themaister** [baldurk/renderdoc#669]
Arch Linux x64.
Commit: 08cbddf06398d69f72af3629f61d95efb48ceff1

vkDebugMarkerSetObjectNameEXT is called on command buffers for reference.

Backtrace:
```
#0  0x00007ffff49c67f0 in raise () at /usr/lib/libpthread.so.0
#1  0x00007ffff6ddd65c in ResourceManager<WrappedVkRes*, TypedRealHandle, VkResourceRecord>::GetLiveID(ResourceId) (this=0x7fffb80516f0, id=...) at /git/renderdoc/renderdoc/core/resource_manager.h:1418
#2  0x00007ffff6eeb6fa in WrappedVulkan::Serialise_vkDebugMarkerSetObjectNameEXT(Serialiser*, VkDevice_T*, VkDebugMarkerObjectNameInfoEXT*) (this=0x7fffb8008290, localSerialiser=0x7fffb8005d20, device=0x0, pNameInfo=0x0)
    at /git/renderdoc/renderdoc/driver/vulkan/wrappers/vk_misc_funcs.cpp:1107
#3  0x00007ffff6d3aed7 in WrappedVulkan::ProcessChunk(unsigned long, VulkanChunkType) (this=0x7fffb8008290, offset=649930695, context=SET_NAME) at /git/renderdoc/renderdoc/driver/vulkan/vk_core.cpp:2264
#4  0x00007ffff6d39824 in WrappedVulkan::ContextProcessChunk(unsigned long, VulkanChunkType) (this=0x7fffb8008290, offset=649930695, chunk=SET_NAME) at /git/renderdoc/renderdoc/driver/vulkan/vk_core.cpp:1940
#5  0x00007ffff6d37d6f in WrappedVulkan::ContextReplayLog(LogState, unsigned int, unsigned int, bool) (this=0x7fffb8008290, readType=READING, startEventID=0, endEventID=0, partial=false)
    at /git/renderdoc/renderdoc/driver/vulkan/vk_core.cpp:1806
#6  0x00007ffff6d36ff6 in WrappedVulkan::ReadLogInitialisation() (this=0x7fffb8008290) at /git/renderdoc/renderdoc/driver/vulkan/vk_core.cpp:1688
#7  0x00007ffff6e41afb in VulkanReplay::ReadLogInitialisation() (this=0x7fffb8008380) at /git/renderdoc/renderdoc/driver/vulkan/vk_replay.cpp:661
#8  0x00007ffff7148ebf in ReplayController::PostCreateInit(IReplayDriver*) (this=0x7fffb8004000, device=0x7fffb8008380) at /git/renderdoc/renderdoc/replay/replay_controller.cpp:1541
#9  0x00007ffff7148d30 in ReplayController::CreateDevice(char const*) (this=0x7fffb8004000, logfile=0x7fffb8007ef0 "/tmp/RenderDoc/lofoten_2017.06.22_07.28.12_frame247.rdc")
    at /git/renderdoc/renderdoc/replay/replay_controller.cpp:1518
#10 0x00007ffff7131dd5 in CaptureFile::OpenCapture(float*) (this=0x7fffb8007f30, progress=0x7fffffffdcac) at /git/renderdoc/renderdoc/replay/capture_file.cpp:105
#11 0x00000000005be162 in ReplayManager::run() (this=0x7fffffffc468) at ../../qrenderdoc/Code/ReplayManager.cpp:410
#12 0x00000000005bb9af in ReplayManager::<lambda()>::operator()(void) const (__closure=0x7fffbc002d70) at ../../qrenderdoc/Code/ReplayManager.cpp:54
#13 0x00000000005bed93 in std::_Function_handler<void(), ReplayManager::OpenCapture(const QString&, float*)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/7.1.1/bits/std_function.h:316
#14 0x00000000005c1108 in std::function<void ()>::operator()() const (this=0x7fffbc002d70) at /usr/include/c++/7.1.1/bits/std_function.h:706
#15 0x00000000005c0c2c in LambdaThread::process() (this=0x7fffbc002d60) at ../../qrenderdoc/Code/QRDUtils.h:754

```

**Comment by baldurk** [comment]
I was handling the case of naming a command buffer before it had started recording, but I think this happens if you name it afterwards (internal jargon: there's no live resource, but there is a replacement active once it's started recording to a baked version). Should be fixed with that commit.

**Comment by Themaister** [comment]
Works. Thanks!
